apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  namespace: hello-world
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <h1>Hello, Class PRO690!</h1>
    </body>
    </html>
